bangazonworkforcemgt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrapp.urls'))
]

hrapp/urls.py
from django.urls import path
from django.conf.urls import include
from hrapp import views
from .views import *

app_name = 'hrapp'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),

    path('employees/', employee_list, name='employee_list'),
    path('employee/form', employee_form, name='employee_form'),
    path('employees/<int:employee_id>/form/', employee_edit_form, name='employee_edit_form'),
    path("employees/<int:employee_id>/", employee_details, name="employee_details"),
    path('employee/trainingprogram/<int:employee_id>/', employee_training_program_form, name="employee_training_program_form"),

    path('departments/', department_list, name='department_list'),
    path('department/form', department_form, name='department_form'),
    path("departments/<int:department_id>/",
         department_details, name="department_details"),
    

    path('computers/', computer_list, name='computer_list'),
    path('computers/form', computer_form, name='computer_form'),
    path('computers/<int:computer_id>/',
         computer_details, name="computer_details"),

    path('training_programs/', training_program_list,
         name='training_program_list'),
    path('training_programs/form', training_program_form,
         name='training_program_form'),
    path("training_programs/<int:training_program_id>/",
         training_program_details, name="training_program_details"),
    path("training_programs/<int:training_program_id>/form/",
         training_program_edit_form, name="training_program_edit_form"),

]

hrapp/models/computer.py
from django.db import models

class Computer(models.Model):
    '''
    description: This class creates a computer and its properties
    author: Joe Shep
    properties:
      make: The make will contain the name of the brand of the computer.
      purchase_date: This property contains the purchase date in string form.
      decomission_date: This property contains the dicomission date in string form.
      employees: This property contains the many to many relationship with the computer/employee model
    '''

    make = models.CharField(max_length=25)
    model = models.CharField(max_length=25)
    purchase_date = models.DateField()
    decommission_date = models.DateField(null=True, blank=True, default=None)
    employees = models.ManyToManyField("Employee", through='EmployeeComputer')

    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

hrapp/models/department.py
from django.db import models

class Department(models.Model):

    department_name = models.CharField(max_length=25)
    budget = models.IntegerField()

    class Meta:
        verbose_name = ("Department")
        verbose_name_plural = ("Departments")

    def __str__(self):
        return f"{self.department_name}"

    def get_absolute_url(self):
        return reverse("Department_detail", kwargs={"pk": self.pk})

hrapp/models/employee.py
from django.db import models
from .department import Department

class Employee(models.Model):

    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    start_date = models.DateField()
    is_supervisor = models.BooleanField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

hrapp/models/employee_computer.py
from django.db import models
from .employee import Employee
from .computer import Computer

class EmployeeComputer(models.Model):
    """
    Creates the join table for the many to many relationship between computers and employees
    Author: Joe Shep
    methods: none
    """

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    computer = models.ForeignKey(Computer, on_delete=models.CASCADE)
    assigned_date = models.DateField()
    unassigned_date = models.DateField(null=True)

hrapp/models/employee_training_program.py
from django.db import models
from .employee import Employee
from .training_program import TrainingProgram

class EmployeeTrainingProgram(models.Model):
    """
    Creates the join table for the many to many relationship between training programs and computers
    Author: Ryan Crowley
    methods: none
    """

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    training_program = models.ForeignKey(TrainingProgram, on_delete=models.CASCADE)

hrapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

hrapp/models/training_program.py
from django.db import models

class TrainingProgram(models.Model):
    '''
    description: 
    author: 
    properties:
      
    '''

    title = models.CharField(max_length=55)
    start_date = models.DateField()
    end_date = models.DateField()
    capacity = models.IntegerField()
    employees = models.ManyToManyField("Employee", through='EmployeeTrainingProgram')

    class Meta:
        verbose_name = ("Training_program")
        verbose_name_plural = ("Training_programs")

    def get_absolute_url(self):
        return reverse("Training_program_detail", kwargs={"pk": self.pk})

hrapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

hrapp/templates/computers/computer_detail.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>{{ computer.make }} {{ computer.model }}</h1>

<a href="{% url 'hrapp:computer_form' %}">Add Computer</a>

<ol>
    <li>
        <p>Purchase Date: {{ computer.purchase_date }}</p>
    </li>
    <li>
        <p>Decommission Date: {{ computer.decommission_date }}</p>
    </li>
</ol>
{% endblock content %}

hrapp/templates/computers/computer_details.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/computers.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<section id="computer-details" class="computer__details__content">
<h1 class="computer__detail__title">{{ computer.make }} {{ computer.model }}</h1>
<ol class="computer__details__content">
    <li>
        <p>Purchase Date: {{ computer.purchase_date }}</p>
    </li>
    {% if computer.decommission_date %}
    <li>
        <p>Decommission Date: {{ computer.decommission_date }}</p>
    </li>
    {% endif %}
    <li>
        <p>Assigned Employee: 
            {% if computer.first_name%}{{ computer.first_name }} {{ computer.last_name }}
            {% elif computer.never_assigned %} (Never Assigned)
            {% else %}None
            {% endif %}</p>
    </li>
</ol>


<div class="computer-button-container">
{% if computer.never_assigned %}
    <form action="{% url 'hrapp:computer_details' computer.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <button onclick="return confirm('Are you sure you want to delete this?')" class="computer-form-button">Delete</button>
    </form>
{% endif %}

<a href="{% url 'hrapp:computer_list' %}">
    <button type="button" class="computer-form-button">Back</button>
</a>
</div>
</section>
{% endblock content %}

hrapp/templates/computers/computer_form.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/computers.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">Add Computer</h1>

<form action="{% url 'hrapp:computer_list' %}" method="post" class="computer-form-container">
    {% csrf_token %}
    <fieldset>
        <label for='make'>Make: </label>
        <input id='make' type='text' name='make' required>
    </fieldset>
    <fieldset>
        <label for='model'>Model: </label>
        <input id='model' type='text' name='model' required>
    </fieldset>
    <fieldset>
        <label for='purchase_date'>Purchase Date: </label>
        <input id='purchase_date' type='date' name='purchase_date' required>
    </fieldset>

    <input type="submit" value="Add Computer" class="computer-form-button"/>
    <a href="{% url 'hrapp:computer_list' %}">
        <button type="button" class="computer-form-button">Cancel</button>
    </a>
</form>
{% endblock content %}

hrapp/templates/computers/computers_list.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/computers.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">Computers</h1><hr />

<a href="{% url 'hrapp:computer_form' %}" class="add-computer">Add Computer</a>

<ol class="computer-list-container">
{% for computer in computers %}
    <li class="computer-list-item">
        <a href="{% url 'hrapp:computer_details' computer.id %}" class="computer-link"><p>{{ computer.make }} {{computer.model}}</p></a>
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/departments/department_detail.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/departments.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<section id="department-details">
<h1 class="department__detail__title">{{ dept_name }}</h1>
<h4>Employees:</h4>
{% for employee in employees%}
<p>{{employee.first_name}} {{employee.last_name}}</p>
{% endfor %}
</section>

{% endblock content %}

hrapp/templates/departments/department_form.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/departments.css' %}" type="text/css" media="screen" />
{% endblock %}
    {% block content %}
    <h1 class="page-header">Add Department</h1>
    <form action="{% url 'hrapp:department_list' %}" method="post" class="department-form-container">
        {% csrf_token %}
        <fieldset>
            <label for="department_name">Name: </label>
            <input id="department_name" type="text" name="department_name" required value="{{ departmentt.department_name }}">
        </fieldset>
        <fieldset>
            <label for="budet">Budget: </label>
            <input id="budget" type="integer" name="budget" required value="{{ department.budget}}">
        </fieldset>
        
        <input type="submit" value="Create" class="department-form-button" />
    
    </form>
    {% endblock %}

</body>

</html>

hrapp/templates/departments/department_list.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/departments.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">Departments</h1><hr />
<a href="{% url 'hrapp:department_form' %}" class="add-department">Add Department</a>
<ol class="department-list-container">
{% for department in departments %}
    <li class="department-list-item">
         <a href="{% url 'hrapp:department_details' department.id %}" class="department-link"><p>{{department.department_name}}</p></a>
        <p>Budget: {{department.budget}}</p>
        <p>Personnel Total: {{ department.dept_total}}</p>
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/employees/employee_training_program_form.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/employees.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
    <h1 class="page-header">Add Training Program</h1>


    <form action="{% url 'hrapp:employee_details' employeeId %}" method="post" class="employee-form-container">
      {% csrf_token %}
      <input id="employee_id" type="hidden" name="employee_id" value="{{employeeId}}" />
 

      <fieldset>
          <label for="training_program_id">Training Program: </label>
          <select id="training_program_id" type="text" name="training_program_id" required>
          {% for program in all_programs %}
              <option value="{{program.id}}">{{program.title}} ({{program.start_date}} thru {{program.end_date}})</option>
          {% endfor %}
          </select> 
      </fieldset>

      <input class="employee-form-button" type="submit" value="Assign" />
      <a href="{% url 'hrapp:employee_details' employeeId %}">
        <button type="button" class="employee-form-button">Cancel</button>
    </a>
    </form>
{% endblock content %}

hrapp/templates/employees/employees_detail.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/employees.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<section id="employee-details" class="employee__details__content">
    <h1 class="employee__detail__title">{{ employee.first_name }} {{ employee.last_name }}</h1>
    <div>Department: {{employee.department_name}}</div>
    {% if computer.make == none or computer.model == none or computer.purchase_date == none %}
        <div>Computer: Not Assigned</div>
    {% else %}
        <div>Computer: {{computer.make}} {{computer.model}} {{computer.purchase_date}}</div>
    {% endif %}

    <h4>Training Programs:</h4>
    <ul>
    {% for program in programs %}
        {% for p in program%}
            <li> {{p.title}} ({{p.start_date}} thru {{p.end_date}})</li>
        {% endfor %}
    {% endfor %}
    </ul>
    <section id="employee-actions" style="display:flex;">
        <form action="{% url 'hrapp:employee_edit_form' employee.id%}" method="GET">
        {% csrf_token%}
            <button class="employee-form-button">Edit</button>
        </form>
    <a href="{% url 'hrapp:employee_training_program_form' employee.id %}" class="add-program"><button class="employee-form-button">Add a Training Program</button></a>
    </section>
</section>
{% endblock %}

hrapp/templates/employees/employees_list.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/employees.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">Employees</h1><hr/>
<a href="{% url 'hrapp:employee_form' %}" class="add-employee">Add Employee</a>

<ol class="employee-list-container">
{% for employee in employees %}
    <li class="employee-list-item">
        <a href="{% url 'hrapp:employee_details' employee.id %}" class="employee-link"> {{ employee.first_name }} {{ employee.last_name }} ({{employee.department_name}})</a>
        {% comment %} Current computer: {{employee.computer}} {% endcomment %}
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/employees/form.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/employees.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}

    {% if employee.id is not None %}
    <h1 class="page-header">Edit Employee</h1>
        <form action="{% url 'hrapp:employee_details' employee.id%}" method="post"class="employee-form-container">
    {% else %}
    <h1 class="page-header">New Employee</h1>
        <form action="{% url 'hrapp:employee_list' %}" method="post" class="employee-form-container">
    {% endif %}
        {% csrf_token %}

      {% if employee.id is None %}
      <fieldset>
          <label for="first_name">First Name: </label>
          <input id="first_name" type="text" name="first_name" value="{{ employee.first_name }}" required>
      </fieldset>
      {% else %}
          <input id="first_name" type="hidden" name="first_name" value="{{ employee.first_name }}" required>
      {% endif %}
                {% csrf_token %}

      <fieldset>
          <label for="last_name">Last Name: </label>
          <input id="last_name" type="text" name="last_name" value="{{ employee.last_name }}" required>
      </fieldset>

      {% if employee.id is None %}
      <fieldset>
          <label for="start_date">Start Date: </label>
          <input id="start_date" type="date" name="start_date" value="{{ employee.start_date }}" required>
      </fieldset>
      {% else %}
          <input id="start_date" type="hidden" name="start_date" value="{{ employee.start_date }}" required>
      {% endif %}
                {% csrf_token %}

      <fieldset>
          <label for="department">Department: </label>
          <select id="department_id" type="text" name="department_id" value="{{ employee.department_id }}" required>
                {% for department in all_departments %}
                    <option value="{{ department.id }}">{{ department.department_name }}</option>
                {% endfor %}
          </select> 
      </fieldset>

      {% if employee.id is None %}
          <input id="is_supervisor" type="hidden" name="is_supervisor" value="{{ employee.is_supervisor }}" required>
      {% else %}
      <fieldset>
          <label for="computer">Computer: </label>
          <select id="computer_id" type="text" name="computer_id" value="{{ computer.id }}" required>
                {% for computer in unassigned_computers %}
                    <option value="{{ computer.id }}">{{ computer.make }}{{ computer.model }}</option>
                {% endfor %}
          </select> 
      </fieldset>
      {% endif %}
                {% csrf_token %}

      {% if employee.id is None %}
      <fieldset>
          <label for="is_supervisor">Superviser: </label>
          <select id="is_supervisor" type="text" name="is_supervisor" value="{{ employee.is_supervisor }}" required>
                    <option value="0">No</option>
                    <option value="1">Yes</option>
          </select> 
      </fieldset>
      {% else %}
          <input id="is_supervisor" type="hidden" name="is_supervisor" value="{{ employee.is_supervisor }}" required>
      {% endif %}
                {% csrf_token %}
      
       {% if employee.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" class="employee-form-button"/>
        {% else %}
            <input type="submit" value="Create" class="employee-form-button"/>
        {% endif %}

      <a href="{% url 'hrapp:employee_details' employee.id %}">
        <button type="button" class="employee-form-button">Back</button>
      </a>
    </form>
{% endblock content %}

hrapp/templates/home.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<section class="home">
<h1 class="page-header">Welcome to the Bangazon Workforce Management System</h1>
<img src="https://storage.needpix.com/rsynced_images/selection-2822237_1280.png" width="60%"></img>
</section>
{% endblock content %}

hrapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="steve-container"><a href="{% url 'hrapp:home' %}" ><img src="../../static/images/homenav.png" id="steve"></img></a></li>
            <li class="navList__route"><a href="{% url 'hrapp:employee_list' %}">Employees</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:department_list' %}">Departments</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:computer_list' %}">Computers</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:training_program_list' %}">Training Programs</a></li>
            {% if user.is_authenticated %}
            <li class="navList__route">Hi {{ user.username }}! <a href="{% url 'hrapp:logout'%}">Logout</a></li>
            {% else %}
            <li class="navList__route">You are not logged in <a href="{% url 'hrapp:login'%}">Login</a></li>
            {% comment %} <a href="{% url 'login' %}">login</a> {% endcomment %}
            {% endif %}



        </ol>
    </nav>



    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

hrapp/templates/training_programs/training_programs_detail.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/training_programs.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}

    <section id="training-program-details" class="training_program__details__content">
        <h1 class="training_program__detail__title">{{ training_details.title }}</h1>
        <h3>Enrolled: {{ training_details.attendees|length }} out of {{ training_details.capacity }}</h3>

        <div>Start Date: {{ training_details.start_date }}</div>
        <div>End Date: {{ training_details.end_date }}</div>
        <ul>
          {% if training_details.attendees %}
            {% for attendee_id, attendee in training_details.attendees %}
              <li>
                <a href="{% url 'hrapp:employee_details' attendee_id %}" class="add-program">{{ attendee }}</a>
              </li>
            {% endfor %}
          {% else %}
            <li>No participants.</li>
          {% endif %}
        </ul>
        <div class="button-container">
        {% if training_details.is_future %}
          <form action="{% url 'hrapp:training_program_edit_form' training_details.id %}" method="GET">
            {% csrf_token %}
            <button class="training-program-form-button buttons">Edit</button>
          </form>
          <form action="{% url 'hrapp:training_program_details' training_details.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="actual_method" value="DELETE">
              <button class="training-program-form-button buttons">Delete</button>
          </form>
        {% endif %}
        <a href="{% url 'hrapp:training_program_list' %}"><button class="training-program-form-button buttons">Back</button></a>
        <div>
    </section>

{% endblock %}

hrapp/templates/training_programs/training_programs_form.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/training_programs.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">
  <span>
    {% if training_program.id is not None %}
    Update
    {% else %}
    Add
    {% endif %}
  </span> Training Program
</h1>
<section class="training-program-form-container">
  {% if training_program.id is not None %}
      <form action="{% url 'hrapp:training_program_details' training_program.id %}" method="post">
  {% else %}
      <form action="{% url 'hrapp:training_program_list' %}" method="post">
  {% endif %}
  {% csrf_token %}
    <fieldset>
      <label for="title">Title: </label>
      <input id="title" type="text" name="title" required value="{{ training_program.title }}">
    </fieldset>
    <fieldset>
      <label for="start_date">Start Date: </label>
      <input id="start_date" type="date" name="start_date" required value="{{ training_program.start_date }}">
    </fieldset>
    <fieldset>
      <label for="end_date">End Date: </label>
      <input id="end_date" type="date" name="end_date" required value="{{ training_program.end_date }}">
    </fieldset>
    <fieldset>
      <label for="capacity">Capacity: </label>
      <input id="capacity" type="number" name="capacity" required value="{{ training_program.capacity }}">
    </fieldset>
    {% if training_program.id is not None %}
      <input type="hidden" name="actual_method" value="PUT">
      <input type="submit" value="Update" class="training-program-form-button"/>
    {% else %}
      <input type="submit" value="Create" class="training-program-form-button"/>
    {% endif %}
    <a href="{% url 'hrapp:training_program_list' %}">
        <button type="button" class="training-program-form-button">Cancel</button>
    </a>
  </form>
</section>
{% endblock content %}

hrapp/templates/training_programs/training_programs_list.html
{% extends 'shared/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/training_programs.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block content %}
<h1 class="page-header">Training Programs</h1><hr />

<div>
 <a href="{% url 'hrapp:training_program_form' %}" class="add-training-program">Add Training Program</a>
 
{% if not viewing_archived %}
    <a href="{% url 'hrapp:training_program_list_archived' %} " class="switch-training-program">View Past Programs</a>
{% else %}
    <a href="{% url 'hrapp:training_program_list' %}" class="switch-training-program">View Current Programs</a>
{% endif %}
</div>

<ol class="training-program-list-container">
{% for training_program in training_programs %}
  {% if not viewing_archived and training_program.is_future %}
    <li class="training-program-list-item">
      <p>
        <a href="{% url 'hrapp:training_program_details' training_program.id %}" class="training-program-link">
        {{ training_program.title }}</a>
      </p>
    </li>
  {% elif viewing_archived and not training_program.is_future %}
    <li class="training-program-list-item">
      <p>
        <a href="{% url 'hrapp:training_program_details' training_program.id %}" class="training-program-link">
        {{ training_program.title }}</a>
      </p>
    </li>
  {% endif %}
{% endfor %}

</ol>

{% endblock content %}